ALTER TABLE lecture ADD COLUMN course_name VARCHAR(255) NOT NULL DEFAULT 'Course';
ALTER TABLE lecture ADD COLUMN is_downloadable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE attendance ADD COLUMN student_name VARCHAR(255) NOT NULL DEFAULT 'Student';